-- Open-source schema for two NEW MySQL 8 databases.
-- Run customer-deploy/scripts/initialize.py; do not import this file directly.
-- No database selection, reset, customer data or administrator credentials are embedded.

-- @database platform
CREATE TABLE `log` (
  `id` int NOT NULL AUTO_INCREMENT,
  `dateTime` datetime DEFAULT NULL COMMENT '日志时间',
  `content` varchar(255) DEFAULT NULL COMMENT '操作内容',
  `userId` int DEFAULT NULL COMMENT '操作用户 ID',
  `type` int DEFAULT NULL COMMENT '日志类型',
  `userIp` varchar(64) DEFAULT NULL COMMENT '用户 IP',
  `requestMethod` varchar(32) DEFAULT NULL COMMENT '请求方法',
  `result` varchar(64) DEFAULT NULL COMMENT '调用结果',
  `logMsg` text COMMENT '日志消息',
  `userAddress` varchar(255) DEFAULT NULL COMMENT '用户地址',
  `userBrowser` varchar(128) DEFAULT NULL COMMENT '浏览器',
  `userSystem` varchar(128) DEFAULT NULL COMMENT '操作系统',
  `requestUrl` varchar(255) DEFAULT NULL COMMENT '请求地址',
  `param` longtext COMMENT '请求参数',
  `old_data` longtext COMMENT '变更前数据',
  `new_data` longtext COMMENT '变更后数据',
  `froms` varchar(64) DEFAULT NULL COMMENT '来源系统',
  `resultData` longtext COMMENT '响应数据',
  PRIMARY KEY (`id`),
  KEY `idx_platform_log_datetime` (`dateTime`),
  KEY `idx_platform_log_user` (`userId`),
  KEY `idx_platform_log_froms` (`froms`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='中台统一操作日志表';

CREATE TABLE `platform_config` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `system_code` varchar(32) NOT NULL DEFAULT 'global' COMMENT '系统编码：global/common/rental/alipay',
  `config_group` varchar(64) NOT NULL DEFAULT 'business' COMMENT '配置分组',
  `config_key` varchar(128) NOT NULL COMMENT '配置键',
  `config_value` text COMMENT '配置值',
  `value_type` varchar(32) NOT NULL DEFAULT 'string' COMMENT 'string/number/boolean/json/secret/cron/url',
  `secret_flag` tinyint NOT NULL DEFAULT '0' COMMENT '是否敏感配置',
  `enabled` tinyint NOT NULL DEFAULT '1' COMMENT '是否启用',
  `display_name` varchar(128) DEFAULT NULL COMMENT '展示名称',
  `remark` varchar(255) DEFAULT NULL COMMENT '说明',
  `sort` int NOT NULL DEFAULT '0' COMMENT '排序',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_platform_config_key` (`system_code`,`config_key`),
  KEY `idx_platform_config_group` (`system_code`,`config_group`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='中台通用配置';

CREATE TABLE `platform_notify_channel` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `channel_code` varchar(64) NOT NULL COMMENT '通道编码',
  `system_code` varchar(32) NOT NULL COMMENT '系统编码',
  `scene_code` varchar(64) NOT NULL COMMENT '场景编码',
  `channel_type` varchar(32) NOT NULL DEFAULT 'feishu' COMMENT '通道类型',
  `app_id` varchar(128) DEFAULT NULL COMMENT '飞书 appId',
  `app_secret` varchar(255) DEFAULT NULL COMMENT '飞书 appSecret',
  `receive_id_type` varchar(32) NOT NULL DEFAULT 'chat_id' COMMENT '接收者类型',
  `receive_id` varchar(128) DEFAULT NULL COMMENT '接收者 ID',
  `enabled` tinyint NOT NULL DEFAULT '1' COMMENT '是否启用',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_platform_notify_channel` (`system_code`,`scene_code`,`channel_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='中台通知通道';

CREATE TABLE `platform_rbac_api_rule` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `button_id` bigint NOT NULL COMMENT '按钮权限 ID',
  `api_method` varchar(16) DEFAULT NULL COMMENT '接口方法',
  `api_path` varchar(255) NOT NULL COMMENT '接口路径',
  `sort` int NOT NULL DEFAULT '0' COMMENT '排序',
  `enabled` tinyint NOT NULL DEFAULT '1' COMMENT '是否启用',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_platform_rbac_api_rule` (`button_id`,`api_method`,`api_path`),
  KEY `idx_platform_rbac_api_rule_button` (`button_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='RBAC 按钮接口规则';

CREATE TABLE `platform_rbac_button` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `system_code` varchar(32) NOT NULL COMMENT '系统编码',
  `page_code` varchar(64) NOT NULL COMMENT '页面编码',
  `button_code` varchar(64) NOT NULL COMMENT '按钮编码',
  `button_name` varchar(96) NOT NULL COMMENT '按钮名称',
  `api_method` varchar(16) DEFAULT NULL COMMENT '关联接口方法',
  `api_path` varchar(255) DEFAULT NULL COMMENT '关联接口路径',
  `sort` int NOT NULL DEFAULT '0' COMMENT '排序',
  `enabled` tinyint NOT NULL DEFAULT '1' COMMENT '是否启用',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_platform_rbac_button` (`system_code`,`page_code`,`button_code`),
  KEY `idx_platform_rbac_button_page` (`system_code`,`page_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='RBAC 功能按钮';

CREATE TABLE `platform_rbac_page` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `system_code` varchar(32) NOT NULL COMMENT '系统编码',
  `page_code` varchar(64) NOT NULL COMMENT '页面编码',
  `page_name` varchar(96) NOT NULL COMMENT '页面名称',
  `route_path` varchar(255) DEFAULT NULL COMMENT '前端路由路径',
  `sort` int NOT NULL DEFAULT '0' COMMENT '排序',
  `enabled` tinyint NOT NULL DEFAULT '1' COMMENT '是否启用',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_platform_rbac_page` (`system_code`,`page_code`),
  KEY `idx_platform_rbac_page_system` (`system_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='RBAC 页面';

CREATE TABLE `platform_rbac_system` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `system_code` varchar(32) NOT NULL COMMENT '系统编码',
  `system_name` varchar(64) NOT NULL COMMENT '系统名称',
  `sort` int NOT NULL DEFAULT '0' COMMENT '排序',
  `enabled` tinyint NOT NULL DEFAULT '1' COMMENT '是否启用',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_platform_rbac_system` (`system_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='RBAC 系统';

CREATE TABLE `platform_role` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `role_code` varchar(64) NOT NULL COMMENT '角色编码',
  `role_name` varchar(96) NOT NULL COMMENT '角色名称',
  `role_desc` varchar(255) DEFAULT NULL COMMENT '角色说明',
  `role_level` int NOT NULL DEFAULT '100' COMMENT '角色等级，数值越小管理权限越高',
  `enabled` tinyint NOT NULL DEFAULT '1' COMMENT '是否启用',
  `built_in` tinyint NOT NULL DEFAULT '0' COMMENT '是否内置角色',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_platform_role_code` (`role_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='RBAC 角色';

CREATE TABLE `platform_role_permission` (
  `role_id` bigint NOT NULL COMMENT '角色 ID',
  `button_id` bigint NOT NULL COMMENT '按钮权限 ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`role_id`,`button_id`),
  KEY `idx_platform_role_permission_button` (`button_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='RBAC 角色按钮权限';

CREATE TABLE `platform_schedule_task` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `task_code` varchar(96) NOT NULL COMMENT '任务编码',
  `system_code` varchar(32) NOT NULL COMMENT '系统编码',
  `task_name` varchar(128) NOT NULL COMMENT '任务名称',
  `cron_expr` varchar(64) NOT NULL COMMENT 'cron 表达式',
  `execute_type` varchar(32) NOT NULL DEFAULT 'HTTP' COMMENT '执行类型',
  `execute_target` varchar(255) DEFAULT NULL COMMENT '执行目标',
  `enabled` tinyint NOT NULL DEFAULT '1' COMMENT '是否启用',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_platform_schedule_task` (`system_code`,`task_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='中台任务配置';

CREATE TABLE `platform_user_role` (
  `user_id` int NOT NULL COMMENT '用户 ID',
  `role_id` bigint NOT NULL COMMENT '角色 ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`,`role_id`),
  KEY `idx_platform_user_role_role` (`role_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='RBAC 用户角色';

CREATE TABLE `user` (
  `id` int NOT NULL AUTO_INCREMENT,
  `realName` varchar(64) DEFAULT NULL COMMENT '用户真实姓名',
  `userName` varchar(64) NOT NULL COMMENT '登录账号',
  `userPwd` varchar(255) NOT NULL COMMENT '登录密码密文',
  `userPhoneNum` varchar(32) DEFAULT NULL COMMENT '用户手机号',
  `userSex` int DEFAULT '0' COMMENT '用户性别，0 男，1 女',
  `creatUserDate` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '用户创建时间',
  `role` int DEFAULT '1' COMMENT '后台角色，0 管理员，1 浏览员',
  `uuid` varchar(64) DEFAULT '-1' COMMENT '小程序用户 UUID，后台账号默认 -1',
  `isNoRequest` int DEFAULT '0' COMMENT '是否禁止请求',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_platform_user_name` (`userName`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='中台统一用户表';

-- @database alipay
CREATE TABLE `category` (
  `category_id` int NOT NULL AUTO_INCREMENT COMMENT '分类ID',
  `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '分类名称',
  `status` int NOT NULL DEFAULT '1' COMMENT '状态：0关闭 1开启',
  PRIMARY KEY (`category_id`) USING BTREE,
  `code` varchar(64) DEFAULT NULL COMMENT '稳定分类编码',
  `parent_code` varchar(64) DEFAULT NULL COMMENT '父分类编码',
  `short_name` varchar(32) DEFAULT NULL COMMENT '小程序简称',
  `description` varchar(512) DEFAULT NULL COMMENT '分类说明',
  `cover_image` varchar(1024) DEFAULT NULL COMMENT '完整 HTTPS 分类封面',
  `icon_name` varchar(64) NOT NULL COMMENT 'antd-mini 分类图标名称',
  `sort_order` int NOT NULL DEFAULT 100 COMMENT '稳定排序',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `uk_category_code` (`code`),
  KEY `idx_category_parent_status_sort` (`parent_code`,`status`,`sort_order`,`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ROW_FORMAT=DYNAMIC COMMENT='商品分类表';

CREATE TABLE `miniapp_banner` (
  `banner_id` int NOT NULL AUTO_INCREMENT COMMENT '轮播图ID',
  `title` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT '标题',
  `description` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '描述',
  `badge` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '角标',
  `image` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT '图片路径或URL',
  `link_type` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT 'none' COMMENT '跳转类型：none/goods/path/url',
  `link_value` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '跳转值',
  `sort_order` int NOT NULL DEFAULT '0' COMMENT '排序值，越大越靠前',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '状态：0停用 1启用',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`banner_id`) USING BTREE,
  KEY `idx_miniapp_banner_status_sort` (`status`,`sort_order`,`banner_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ROW_FORMAT=DYNAMIC COMMENT='小程序首页轮播图';

CREATE TABLE `goods` (
  `goods_id` int NOT NULL AUTO_INCREMENT COMMENT '商品ID',
  `title` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '商品标题',
  `cover` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '商品封面',
  `description` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '商品简述',
  `slides` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT '轮播图，逗号分隔',
  `min_price` int NOT NULL DEFAULT '0' COMMENT '最低价格（分）',
  `max_price` int NOT NULL DEFAULT '999999' COMMENT '最高价格（分）',
  `deposit` int NOT NULL DEFAULT '0' COMMENT '商品押金（分）',
  `delivery_type` int NOT NULL DEFAULT '1' COMMENT '配送方式：1包邮 2自取',
  `activity_text` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '活动描述（70字内）',
  `spec_params` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '规格参数（富文本）',
  `rental_guide` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '租赁必读（富文本）',
  `detail` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '商品介绍（富文本）',
  `status` int NOT NULL DEFAULT '1' COMMENT '状态：0下架 1上架',
  `is_public` int NOT NULL DEFAULT '1' COMMENT '是否公开：1公开 2不公开',
  `qrcode` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '商品二维码',
  `sales` int NOT NULL DEFAULT '0' COMMENT '销量',
  `sort_order` bigint DEFAULT NULL COMMENT '排序值',
  `support_pickup` int NOT NULL DEFAULT '0' COMMENT '支持线下取货：0支持 1不支持',
  `freight` int DEFAULT '0' COMMENT '运费（分）',
  `support_buyout` int DEFAULT '0' COMMENT '支持买断：0不支持 1支持',
  `alipay_goods_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '支付宝商品ID',
  `alipay_category_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '支付宝普通商品类目ID',
  `alipay_rent_category_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '支付宝租赁信用类目ID',
  `item_fineness` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT 'secondHand' COMMENT '支付宝商品成色：wholeNew全新 secondHand二手',
  `item_fineness_grade` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '95new' COMMENT '支付宝商品成色等级：99new/95new/90new/80new/70new',
  `alipay_image_dir_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '支付宝图片目录ID',
  `alipay_audit_status` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '支付宝商品审核状态，来源于商品状态通知 audit_status',
  `alipay_spu_status` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '支付宝商品SPU状态，来源于商品查询或状态通知 spu_status',
  `alipay_status_reason` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '支付宝商品审核驳回、冻结等状态原因原文',
  `alipay_status_updated_at` datetime DEFAULT NULL COMMENT '支付宝商品状态最近更新时间',
  PRIMARY KEY (`goods_id`) USING BTREE,
  `category_code` varchar(64) DEFAULT NULL COMMENT '叶子分类编码',
  `brand` varchar(128) DEFAULT NULL,
  `model_name` varchar(128) DEFAULT NULL,
  `device_type` varchar(64) DEFAULT NULL,
  `default_rent_unit` varchar(16) DEFAULT NULL COMMENT '显式默认单位；为空时按主 SKU 推导',
  `featured` tinyint NOT NULL DEFAULT 0,
  `featured_sort` bigint NOT NULL DEFAULT 0,
  KEY `idx_goods_public_category_sort` (`status`,`is_public`,`category_code`,`sort_order`,`goods_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ROW_FORMAT=DYNAMIC COMMENT='商品表';

CREATE TABLE `goods_sku` (
  `sku_id` int NOT NULL AUTO_INCREMENT COMMENT '规格ID',
  `goods_id` int NOT NULL COMMENT '所属商品ID',
  `cover` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT '规格封面图',
  `title` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '规格标题',
  `description` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '规格描述',
  `daily_rent` int NOT NULL DEFAULT '0' COMMENT '日租金（分）',
  `rent_periods` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT '可选租期，逗号分隔',
  `stock` int NOT NULL DEFAULT '0' COMMENT '库存',
  `allow_deposit_free` int NOT NULL DEFAULT '1' COMMENT '允许免押：1是 2否',
  `deposit` int NOT NULL DEFAULT '0' COMMENT '押金（分）',
  `allow_buyout` int NOT NULL DEFAULT '1' COMMENT '允许买断：1是 0否',
  `buyout_price` int NOT NULL DEFAULT '0' COMMENT '买断价格（分）',
  `min_rent_days` int NOT NULL DEFAULT '0' COMMENT '最小租赁天数',
  `max_rent_days` int NOT NULL DEFAULT '999' COMMENT '最大租赁天数',
  `penalty_per_day` int NOT NULL DEFAULT '0' COMMENT '每日违约金（分）',
  `billing_cycle` int NOT NULL DEFAULT '1' COMMENT '扣款类型：1一次性 2月付 3年付',
  `installment_enabled` tinyint NOT NULL DEFAULT '0' COMMENT '是否开启分期：1是 0否',
  `installment_periods` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '1' COMMENT '可选支付期数，逗号分隔，1表示不分期',
  `rent_to_own` int DEFAULT NULL COMMENT '租转售标记',
  `alipay_sku_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '支付宝SKU ID',
  PRIMARY KEY (`sku_id`) USING BTREE,
  KEY `idx_goods_sku_goods_stock_rent` (`goods_id`,`stock`,`daily_rent`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ROW_FORMAT=DYNAMIC COMMENT='商品规格表';

CREATE TABLE `installment_plan` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `order_id` int DEFAULT NULL COMMENT '关联订单ID',
  `period_no` int DEFAULT NULL COMMENT '期数编号',
  `period_amount` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '分期金额',
  `buyout_price` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '买断价格',
  `plan_pay_time` datetime DEFAULT NULL COMMENT '计划支付时间',
  `status` int DEFAULT '0' COMMENT '支付状态：0未支付 1已支付',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ROW_FORMAT=DYNAMIC COMMENT='分期计划表';

CREATE TABLE `rent_buyout_payment` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `order_id` int NOT NULL,
  `order_no` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL,
  `rent_order_id` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL,
  `attr_id` int DEFAULT NULL,
  `user_uuid` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `buyout_price` int NOT NULL DEFAULT '0' COMMENT '买断价格，单位分',
  `out_installment_order_id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '支付宝买断分期单外部请求号，同时作为支付 out_trade_no',
  `installment_order_id` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '支付宝买断分期单号',
  `payment_trade_no` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '支付宝买断支付交易号',
  `status` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'CREATING',
  `last_error` varchar(1024) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `raw_response` longtext COLLATE utf8mb4_unicode_ci,
  `raw_notify` longtext COLLATE utf8mb4_unicode_ci,
  `paid_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_rent_buyout_payment_order` (`order_id`),
  UNIQUE KEY `uk_rent_buyout_payment_out_installment` (`out_installment_order_id`),
  KEY `idx_rent_buyout_payment_trade_no` (`payment_trade_no`),
  KEY `idx_rent_buyout_payment_status` (`status`,`updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `iphone_push_device` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `user_id` int DEFAULT NULL COMMENT '中台用户ID',
  `user_name` varchar(128) DEFAULT NULL COMMENT '中台用户名',
  `platform` varchar(32) NOT NULL DEFAULT 'ios' COMMENT '设备平台',
  `provider` varchar(32) NOT NULL DEFAULT 'apns' COMMENT '推送提供方',
  `client_id` varchar(256) NOT NULL COMMENT 'APNs device token，兼容历史 clientId 字段',
  `device_token` varchar(256) DEFAULT NULL COMMENT '原始设备 token',
  `app_version` varchar(64) DEFAULT NULL COMMENT 'APP版本',
  `os_version` varchar(64) DEFAULT NULL COMMENT '系统版本',
  `enabled` tinyint NOT NULL DEFAULT '1' COMMENT '是否启用',
  `last_seen_at` datetime DEFAULT NULL COMMENT '最后上报时间',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_iphone_push_client_id` (`client_id`),
  KEY `idx_iphone_push_user` (`user_id`,`enabled`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='iPhone APP推送设备绑定';

CREATE TABLE `iphone_push_message` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `order_id` int DEFAULT NULL COMMENT '订单ID',
  `order_no` varchar(128) DEFAULT NULL COMMENT '订单号',
  `target_user_id` int DEFAULT NULL COMMENT '指定中台用户，为空表示全部启用用户',
  `title` varchar(128) NOT NULL COMMENT '推送标题',
  `content` varchar(512) NOT NULL COMMENT '推送内容',
  `status` varchar(32) NOT NULL DEFAULT 'PENDING' COMMENT '发送状态',
  `retry_count` int NOT NULL DEFAULT '0' COMMENT '重试次数',
  `last_error` varchar(512) DEFAULT NULL COMMENT '最近失败原因',
  `sent_at` datetime DEFAULT NULL COMMENT '发送时间',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_iphone_push_message_status` (`status`,`created_at`),
  KEY `idx_iphone_push_message_order` (`order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='iPhone APP推送消息';

CREATE TABLE `order_operation_log` (
  `log_id` bigint NOT NULL AUTO_INCREMENT COMMENT '日志ID',
  `order_id` int DEFAULT NULL COMMENT '订单ID',
  `order_no` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '订单编号',
  `operation_type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT '操作类型',
  `operation_desc` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '操作描述',
  `status_before` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '操作前状态',
  `status_after` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '操作后状态',
  `request_body` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '请求数据',
  `response_body` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '响应数据',
  `success` int DEFAULT NULL COMMENT '是否成功',
  `fail_reason` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '失败原因',
  `operator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '操作人',
  `created_at` bigint DEFAULT NULL COMMENT '操作时间',
  PRIMARY KEY (`log_id`) USING BTREE,
  KEY `idx_order_id` (`order_id`) USING BTREE,
  KEY `idx_order_no` (`order_no`) USING BTREE,
  KEY `idx_operation_type` (`operation_type`) USING BTREE,
  KEY `idx_created_at` (`created_at`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ROW_FORMAT=DYNAMIC COMMENT='订单操作日志表';

CREATE TABLE `periodic_report` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '主键',
  `report_type` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '报表类型：WEEK/MONTH/YEAR',
  `period_key` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '周期标识',
  `period_start_time` datetime NOT NULL COMMENT '周期开始时间',
  `period_end_time` datetime NOT NULL COMMENT '周期结束时间',
  `report_title` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '报表标题',
  `total_revenue` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '总收入',
  `sales_count` int NOT NULL DEFAULT '0' COMMENT '订单数',
  `profit_amount` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '盈利口径',
  `loss_amount` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '亏损口径',
  `extra_metric_1` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '扩展指标1',
  `extra_metric_2` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '扩展指标2',
  `extra_metric_3` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '扩展指标3',
  `generate_mode` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT 'AUTO' COMMENT '生成方式：AUTO/MANUAL',
  `content_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '报表快照',
  `generated_at` datetime NOT NULL COMMENT '生成时间',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_report_period` (`report_type`,`period_start_time`,`period_end_time`) USING BTREE,
  KEY `idx_report_type_generated_at` (`report_type`,`generated_at`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC COMMENT='周期报表';

CREATE TABLE `rent_aftersale_notify_record` (
  `id` int NOT NULL AUTO_INCREMENT,
  `notify_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '支付宝通知ID，作为通知幂等主键',
  `msg_method` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '支付宝消息方法名',
  `out_order_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '商户订单号',
  `order_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '交易组件订单号',
  `aftersale_id` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '支付宝售后单号',
  `out_aftersale_id` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '商户售后单号',
  `aftersale_status` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '支付宝售后单当前状态',
  `operation_type` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '本次触发通知的售后操作类型',
  `payload_json` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '原始通知报文，便于排障',
  `process_status` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '通知处理状态：PROCESSING/SUCCESS/FAILED',
  `fail_reason` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '处理失败原因',
  `created_at` bigint NOT NULL COMMENT '创建时间戳',
  `updated_at` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_notify_id` (`notify_id`) USING BTREE,
  KEY `idx_out_order_id` (`out_order_id`) USING BTREE,
  KEY `idx_aftersale_id` (`aftersale_id`) USING BTREE,
  KEY `idx_out_aftersale_id` (`out_aftersale_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC COMMENT='支付宝租赁售后通知流水表';

CREATE TABLE `rent_deposit_deduct_record` (
  `id` int NOT NULL AUTO_INCREMENT,
  `order_id` int NOT NULL COMMENT '内部订单ID',
  `order_no` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '商户订单号',
  `auth_no` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '支付宝资金授权号',
  `aftersale_no` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '支付宝售后单号',
  `out_aftersale_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '商户售后单号',
  `confirm_request_no` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '售后确认请求号',
  `out_trade_no` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '赔付支付外部请求号',
  `operation_no` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '支付宝授权操作流水号',
  `trade_no` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '支付宝交易号',
  `out_request_no` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '商户本次扣减请求号',
  `fee_type` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '费用类型：INDEMNITY/LATE_FEE',
  `reason_code` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '赔付或违约金原因码',
  `deduct_amount` int NOT NULL COMMENT '本次扣减金额，单位分',
  `before_remaining_deposit` int NOT NULL COMMENT '扣减前剩余押金，单位分',
  `after_remaining_deposit` int DEFAULT NULL COMMENT '扣减后剩余押金，单位分',
  `reason` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '扣减原因',
  `remark` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '备注',
  `operator_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '操作人ID',
  `operator_name` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '操作人名称',
  `alipay_sub_code` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '支付宝子错误码',
  `alipay_sub_msg` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '支付宝子错误描述',
  `aftersale_status` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '支付宝售后单当前状态',
  `last_operation_type` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '最近一次售后通知对应的操作类型',
  `source_type` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '售后发起来源：ZHIMA_RENT/MERCHANT',
  `need_operation` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '下一步是否仍需商家操作',
  `last_notify_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '最近一次成功消费的支付宝通知ID',
  `status` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT 'PROCESSING/SUCCESS/FAILED',
  `created_at` bigint NOT NULL COMMENT '创建时间戳',
  `updated_at` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_out_request_no` (`out_request_no`) USING BTREE,
  UNIQUE KEY `uk_out_aftersale_id` (`out_aftersale_id`) USING BTREE,
  UNIQUE KEY `uk_out_trade_no` (`out_trade_no`) USING BTREE,
  KEY `idx_order_id` (`order_id`) USING BTREE,
  KEY `idx_order_no` (`order_no`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC COMMENT='押金赔付/违约金扣减记录表';

CREATE TABLE `rent_order` (
  `order_id` int NOT NULL AUTO_INCREMENT COMMENT '订单ID',
  `sku_id` int DEFAULT NULL COMMENT '规格ID',
  `sku_title` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '规格标题',
  `daily_rent` int NOT NULL DEFAULT '0' COMMENT '日租金（分）',
  `order_no` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT '订单编号',
  `request_no` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '请求编号',
  `auth_no` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '授权号',
  `payment_trade_no` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '支付宝租赁租金支付交易号',
  `operation_no` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '操作流水号',
  `quantity` int NOT NULL DEFAULT '1' COMMENT '商品数量',
  `deposit` int NOT NULL DEFAULT '0' COMMENT '押金（分）',
  `overdue_fee` int NOT NULL DEFAULT '0' COMMENT '逾期费用（分）',
  `damage_fee` int NOT NULL DEFAULT '0' COMMENT '赔偿金（分）',
  `paid_amount` int NOT NULL DEFAULT '0' COMMENT '已付金额（分）',
  `total_amount` int NOT NULL DEFAULT '0' COMMENT '订单总额（分）',
  `goods_id` int NOT NULL COMMENT '商品ID',
  `goods_cover` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT '商品封面',
  `delivery_type` int DEFAULT '1' COMMENT '配送方式：1包邮 2自取',
  `goods_title` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '商品标题',
  `rent_start` bigint NOT NULL COMMENT '起租日期',
  `rent_end` bigint NOT NULL COMMENT '截止日期',
  `rent_days` int NOT NULL DEFAULT '0' COMMENT '总租赁天数',
  `created_at` bigint NOT NULL COMMENT '创建时间',
  `message` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '订单留言',
  `last_paid_at` bigint DEFAULT '0' COMMENT '上次付款时间',
  `express_no` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '快递单号',
  `express_company` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '快递公司',
  `express_code` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '快递公司代码',
  `user_id` int NOT NULL COMMENT '用户ID',
  `user_phone` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT '用户手机号',
  `user_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT '用户昵称',
  `address` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT '收货地址',
  `status` int NOT NULL DEFAULT '1' COMMENT '状态：0取消 1未付款 2待发货 3待收货 4租赁中 5逾期 6退款 7已归还 8归还中 9待解冻 10待起租 11待到店 12退款审核 13退款审核通过',
  `bill_info` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '账单信息',
  `received_at` bigint DEFAULT NULL COMMENT '收货时间',
  `shipped_at` bigint DEFAULT '0' COMMENT '发货时间',
  `billing_cycle` int DEFAULT NULL COMMENT '扣款类型：1一次性 2月付 3年付',
  `next_billing_at` bigint DEFAULT '0' COMMENT '下次扣款时间',
  `penalty_per_day` int DEFAULT '0' COMMENT '每日违约金（分）',
  `current_period` int DEFAULT '1' COMMENT '当前期数',
  `user_uuid` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '用户UUID',
  `total_periods` int DEFAULT NULL COMMENT '总期数',
  `order_type` int DEFAULT '0' COMMENT '订单类型：0普通',
  `first_period_amount` int DEFAULT '0' COMMENT '首期金额（分）',
  `per_period_amount` int DEFAULT '0' COMMENT '每期金额（分）',
  `last_period_amount` int DEFAULT '0' COMMENT '尾期金额（分）',
  `remaining_deposit` int DEFAULT NULL COMMENT '剩余押金（分）',
  `billing_date` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '扣款日期',
  `rent_to_own` int DEFAULT '0' COMMENT '租转售标记',
  `freight` int DEFAULT '0' COMMENT '运费（分）',
  `support_pickup` int DEFAULT '1' COMMENT '线下取货：0是 1否',
  `pickup_address` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '取货地址',
  `coupon_info` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '优惠券信息（JSON）',
  `remaining_coupon` int DEFAULT '0' COMMENT '剩余优惠券金额（分）',
  `return_info` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '归还信息（JSON）',
  `id_card_front` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '身份证国徽面',
  `id_card_portrait` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '身份证人像面',
  `frozen_credit` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '累计冻结信用押金',
  `remaining_credit` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '剩余信用金额',
  `frozen_fund` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '累计冻结资金',
  `paid_credit` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '累计支付信用金额',
  `paid_fund` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '累计支付资金',
  `remaining_fund` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '剩余资金',
  `total_paid` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '累计支付总额',
  `remark` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '备注',
  `remaining_frozen` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '剩余冻结总额',
  `updated_at` date DEFAULT NULL COMMENT '修改时间',
  `source_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '来源追踪ID',
  `alipay_order_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '支付宝订单号',
  `merchant_order_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '商家订单号',
  `alipay_status` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '支付宝状态：CREATED/SIGNED/APPROVED/DELIVERED/RECEIVED/RETURN_DELIVERED/RETURN_RECEIVED/FINISHED/CLOSED',
  `contract_no` varchar(64) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '租赁协议编号',
  `contract_version` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '租赁协议版本',
  `contract_agreed_at` bigint DEFAULT NULL COMMENT '用户确认协议时间',
  `contract_pdf_url` varchar(512) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '租赁协议PDF完整URL',
  `contract_pdf_path` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '租赁协议PDF相对路径',
  `contract_snapshot_json` text COLLATE utf8mb4_bin COMMENT '租赁协议签署快照JSON',
  PRIMARY KEY (`order_id`) USING BTREE,
  `contract_alipay_file_id` varchar(128) DEFAULT NULL COMMENT '支付宝合同文件file_id',
  `contract_alipay_sync_status` varchar(32) DEFAULT NULL COMMENT '合同回传支付宝状态：SUCCESS/FAILED',
  `contract_alipay_synced_at` bigint DEFAULT NULL COMMENT '合同最近回传支付宝时间戳',
  `contract_alipay_sync_error` varchar(1024) DEFAULT NULL COMMENT '合同回传支付宝失败原因',
  KEY `idx_rent_order_user_uuid_created_at` (`user_uuid`, `created_at`),
  KEY `idx_rent_order_goods_id` (`goods_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ROW_FORMAT=DYNAMIC COMMENT='租赁订单表';

CREATE TABLE `rent_order_relet_relation` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `child_order_id` int NOT NULL COMMENT '续租子单本地订单ID',
  `child_order_no` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '续租子单本地订单号',
  `child_rent_order_id` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '续租子单支付宝租赁订单号',
  `parent_order_id` int NOT NULL COMMENT '直接父单本地订单ID',
  `parent_order_no` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '直接父单本地订单号',
  `parent_rent_order_id` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '直接父单支付宝租赁订单号',
  `origin_order_id` int NOT NULL COMMENT '根单本地订单ID',
  `origin_order_no` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '根单本地订单号',
  `origin_rent_order_id` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '根单支付宝租赁订单号',
  `user_uuid` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '用户UUID',
  `renew_duration` int NOT NULL COMMENT '本次续租天数',
  `original_rent_end` bigint DEFAULT NULL COMMENT '父单原租赁结束时间',
  `relet_rent_start` bigint DEFAULT NULL COMMENT '续租子单开始时间',
  `relet_rent_end` bigint DEFAULT NULL COMMENT '续租子单结束时间',
  `status` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT 'ACTIVE' COMMENT '关系状态：ACTIVE/CLOSED',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_relet_child_order_id` (`child_order_id`) USING BTREE,
  UNIQUE KEY `uk_relet_child_order_no` (`child_order_no`) USING BTREE,
  KEY `idx_relet_child_rent_order_id` (`child_rent_order_id`) USING BTREE,
  KEY `idx_relet_parent_order_id` (`parent_order_id`) USING BTREE,
  KEY `idx_relet_parent_order_no` (`parent_order_no`) USING BTREE,
  KEY `idx_relet_origin_order_id` (`origin_order_id`) USING BTREE,
  KEY `idx_relet_origin_rent_order_id` (`origin_rent_order_id`) USING BTREE,
  KEY `idx_relet_user_status` (`user_uuid`,`status`) USING BTREE,
  KEY `idx_relet_child_order_user_uuid` (`child_order_id`, `user_uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC COMMENT='支付宝租赁订单续租关系表';

CREATE TABLE `rent_order_return_record` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `order_id` int NOT NULL COMMENT '本地租赁订单ID',
  `order_no` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '本地业务订单号',
  `rent_order_id` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '支付宝交易组件订单号',
  `user_uuid` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '小程序用户支付宝唯一标识',
  `return_type` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '寄回方式：ONLINE_EXPRESS/OFFLINE等',
  `express_code` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '快递公司编码，传给支付宝delivery_id',
  `express_company` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '快递公司名称，后台展示用',
  `express_no` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '寄回快递单号，传给支付宝waybill_id',
  `photo_urls` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '寄回照片JSON数组，保存OSS key或URL',
  `detail_remark` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '用户填写的寄回详情说明',
  `status` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT 'SUBMITTED' COMMENT '记录状态：SUBMITTED/SEND_SUCCESS/SEND_FAILED',
  `fail_reason` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '履约失败原因',
  `submitted_at` bigint DEFAULT NULL COMMENT '用户提交寄回信息的毫秒时间戳',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_return_record_order_id` (`order_id`) USING BTREE,
  KEY `idx_return_record_order_no` (`order_no`) USING BTREE,
  KEY `idx_return_record_express_no` (`express_no`) USING BTREE,
  KEY `idx_return_record_status` (`status`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC COMMENT='支付宝租赁用户寄回记录表';

CREATE TABLE `rent_sys_config` (
  `id` int NOT NULL AUTO_INCREMENT,
  `config_key` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '配置键，唯一',
  `config_value` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '配置值',
  `config_name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '配置中文名称',
  `remark` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '说明（干什么用的）',
  `sort` int DEFAULT '0' COMMENT '排序',
  `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_config_key` (`config_key`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC COMMENT='租赁系统码表';

CREATE TABLE `user` (
  `user_id` int NOT NULL AUTO_INCREMENT COMMENT '用户ID',
  `nickname` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT '新用户' COMMENT '用户昵称',
  `avatar` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '用户头像',
  `openid` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'OpenID（已弃用）',
  `uuid` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '支付宝用户UUID',
  `alipay_user_id` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '支付宝用户ID（2088开头）',
  `address` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '默认收货地址',
  `phone` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '手机号码',
  `birthday` bigint DEFAULT NULL COMMENT '出生日期时间戳',
  `account` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '登录账号',
  `password` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '登录密码',
  `share_cover` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT 'default/zffm.jpg' COMMENT '转发封面',
  `share_text` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '转发文字',
  `balance` int NOT NULL DEFAULT '0' COMMENT '用户余额（分）',
  `total_balance` int NOT NULL DEFAULT '0' COMMENT '累计余额（分）',
  `created_at` bigint NOT NULL DEFAULT '0' COMMENT '创建时间',
  `dist_created_at` bigint NOT NULL DEFAULT '0' COMMENT '绑定分销上级时间',
  `parent_user_id` int NOT NULL DEFAULT '0' COMMENT '一级上级用户ID',
  `grandparent_user_id` int NOT NULL DEFAULT '0' COMMENT '二级上级用户ID',
  `qrcode` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '0' COMMENT '用户二维码',
  `merchant_phone` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '代理商联系电话',
  `pickup_location` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '取件地址（JSON）',
  `return_location` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '归还地址（JSON）',
  `return_contact_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '归还收件人姓名',
  `return_contact_phone` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '归还收件人电话',
  `is_blocked` int DEFAULT '0' COMMENT '是否封禁：0否 1是',
  `real_name` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '真实姓名',
  `id_card` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '身份证号',
  PRIMARY KEY (`user_id`) USING BTREE,
  KEY `idx_user_alipay_user_id` (`alipay_user_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ROW_FORMAT=DYNAMIC COMMENT='用户表';

CREATE TABLE `alipay_goods_sync_log` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `good_id` int NOT NULL COMMENT '本地商品ID',
  `task_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '同步任务ID',
  `trigger_type` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '触发来源：manual手动，auto自动',
  `sync_status` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '同步状态：QUEUED/RUNNING/SUCCESS/FAILED/SKIPPED',
  `sync_mode` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '实际同步模式：create/modify/direct_modify等',
  `alipay_item_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '支付宝商品ID',
  `message` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '同步日志摘要或失败原因',
  `detail_json` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '同步结果详情JSON',
  `started_at` datetime DEFAULT NULL COMMENT '同步开始时间',
  `finished_at` datetime DEFAULT NULL COMMENT '同步结束时间',
  `duration_ms` bigint DEFAULT NULL COMMENT '同步耗时毫秒数',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_alipay_goods_sync_log_task_id` (`task_id`) USING BTREE,
  KEY `idx_alipay_goods_sync_log_good_id` (`good_id`) USING BTREE,
  KEY `idx_alipay_goods_sync_log_good_status` (`good_id`,`sync_status`) USING BTREE,
  CONSTRAINT `fk_alipay_goods_sync_log_good` FOREIGN KEY (`good_id`) REFERENCES `goods` (`goods_id`) ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC COMMENT='支付宝商品同步日志表';

CREATE TABLE `order_contract` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `order_id` int NOT NULL,
  `provider` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'esign',
  `contract_no` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `flow_id` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `signer_id` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `file_id` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `contract_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `sign_url` text COLLATE utf8mb4_unicode_ci,
  `view_url` text COLLATE utf8mb4_unicode_ci,
  `download_url` text COLLATE utf8mb4_unicode_ci,
  `pdf_url` text COLLATE utf8mb4_unicode_ci,
  `signed_at` datetime DEFAULT NULL,
  `expire_at` datetime DEFAULT NULL,
  `raw_response` longtext COLLATE utf8mb4_unicode_ci,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_order_contract_order` (`order_id`),
  UNIQUE KEY `uk_order_contract_flow` (`flow_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `installment_bill` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `order_id` int NOT NULL,
  `bill_no` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL,
  `period_no` int NOT NULL,
  `period_total` int NOT NULL,
  `amount` int NOT NULL DEFAULT '0',
  `paid_amount` int NOT NULL DEFAULT '0',
  `due_date` datetime DEFAULT NULL,
  `paid_at` datetime DEFAULT NULL,
  `status` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `payment_trade_no` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `out_trade_no` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `last_error` varchar(1024) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_installment_bill_order_period` (`order_id`,`period_no`),
  UNIQUE KEY `uk_installment_bill_no` (`bill_no`),
  UNIQUE KEY `uk_installment_bill_out_trade_no` (`out_trade_no`),
  KEY `idx_installment_bill_due` (`status`,`due_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `withhold_agreement` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `order_id` int NOT NULL,
  `user_id` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `provider` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'alipay',
  `agreement_no` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `external_agreement_no` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `sign_url` text COLLATE utf8mb4_unicode_ci,
  `sign_str` text COLLATE utf8mb4_unicode_ci,
  `signed_at` datetime DEFAULT NULL,
  `next_deduct_at` datetime DEFAULT NULL,
  `raw_response` longtext COLLATE utf8mb4_unicode_ci,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_withhold_order` (`order_id`),
  UNIQUE KEY `uk_withhold_agreement_no` (`agreement_no`),
  UNIQUE KEY `uk_withhold_external_no` (`external_agreement_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `external_callback_log` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `provider` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `event_type` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `biz_id` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `payload` longtext COLLATE utf8mb4_unicode_ci,
  `handled` tinyint(1) NOT NULL DEFAULT '0',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_external_callback_biz` (`provider`,`event_type`,`biz_id`),
  KEY `idx_external_callback_created` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `rent_aftersale_sync_snapshot` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `order_id` int DEFAULT NULL COMMENT '本地订单ID',
  `order_no` varchar(64) DEFAULT NULL COMMENT '本地订单号',
  `rent_order_id` varchar(128) DEFAULT NULL COMMENT '支付宝租赁订单号',
  `aftersale_no` varchar(128) DEFAULT NULL COMMENT '支付宝售后单号',
  `out_aftersale_id` varchar(128) DEFAULT NULL COMMENT '商户外部售后单号',
  `source_type` varchar(32) DEFAULT NULL COMMENT '售后来源：MERCHANT/ZHIMA_RENT',
  `aftersale_type` varchar(64) DEFAULT NULL COMMENT '售后类型',
  `aftersale_status` varchar(32) DEFAULT NULL COMMENT '支付宝售后状态',
  `finished` tinyint(1) DEFAULT NULL COMMENT '支付宝侧是否完结',
  `apply_time` datetime DEFAULT NULL COMMENT '支付宝侧申请时间',
  `last_operation_type` varchar(64) DEFAULT NULL COMMENT '最近一次操作类型',
  `next_operation_types` varchar(512) DEFAULT NULL COMMENT '下一步可操作动作，逗号分隔',
  `need_operation` varchar(8) DEFAULT NULL COMMENT '是否需要商家处理',
  `fee_type` varchar(64) DEFAULT NULL COMMENT '费用类型',
  `reason_code` varchar(64) DEFAULT NULL COMMENT '推断出的本地原因码',
  `deduct_amount` int DEFAULT NULL COMMENT '售后金额，单位分',
  `reason_description` varchar(512) DEFAULT NULL COMMENT '原因描述',
  `matched_deduct_record_id` int DEFAULT NULL COMMENT '匹配到的本地扣减记录ID',
  `match_status` varchar(32) NOT NULL DEFAULT 'MISSING_LOCAL' COMMENT '对账状态',
  `import_status` varchar(32) NOT NULL DEFAULT 'PENDING_IMPORT' COMMENT '导入状态',
  `payload_json` mediumtext COMMENT '支付宝原始售后快照JSON',
  `fail_reason` varchar(1024) DEFAULT NULL COMMENT '同步或导入失败原因',
  `synced_at` datetime DEFAULT NULL COMMENT '最近同步时间',
  `imported_at` datetime DEFAULT NULL COMMENT '最近导入时间',
  `created_at` bigint DEFAULT NULL COMMENT '创建时间戳',
  `updated_at` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_aftersale_no` (`aftersale_no`),
  KEY `idx_order_id` (`order_id`),
  KEY `idx_order_no` (`order_no`),
  KEY `idx_out_aftersale_id` (`out_aftersale_id`),
  KEY `idx_match_import` (`match_status`, `import_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='支付宝租赁售后同步快照表';

CREATE TABLE `rent_catalog_goods_category_mapping` (
  goods_id int NOT NULL,
  category_code varchar(64) NOT NULL,
  review_status varchar(16) NOT NULL DEFAULT 'PENDING',
  reviewer varchar(128) DEFAULT NULL,
  reviewed_at datetime DEFAULT NULL,
  applied_at datetime DEFAULT NULL,
  note varchar(512) DEFAULT NULL,
  PRIMARY KEY (goods_id),
  KEY idx_catalog_mapping_status (review_status, category_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='人工核对的历史商品分类映射';

CREATE TABLE `rent_catalog_admin_operation` (
  id bigint NOT NULL AUTO_INCREMENT,
  idempotency_key varchar(128) DEFAULT NULL COMMENT '高风险操作幂等键',
  action varchar(32) NOT NULL,
  resource_code varchar(64) DEFAULT NULL,
  operator_name varchar(128) DEFAULT NULL,
  request_summary varchar(1024) DEFAULT NULL,
  result_summary varchar(1024) DEFAULT NULL,
  success tinyint NOT NULL DEFAULT 0,
  fail_reason varchar(512) DEFAULT NULL,
  created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_catalog_operation_idempotency (idempotency_key, action),
  KEY idx_catalog_operation_resource_time (resource_code, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='自有小程序目录后台操作审计';
