server:
  port: 8761

spring:
  application:
    name: equipment-eureka-server
  profiles:
    active: @env.profile@

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
