CREATE TABLE IF NOT EXISTS `rent_aftersale_sync_snapshot` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `order_id` int DEFAULT NULL COMMENT '本地订单ID',
  `order_no` varchar(64) DEFAULT NULL COMMENT '本地订单号',
  `rent_order_id` varchar(128) DEFAULT NULL COMMENT '支付宝租赁订单号',
  `aftersale_no` varchar(128) DEFAULT NULL COMMENT '支付宝售后单号',
  `out_aftersale_id` varchar(128) DEFAULT NULL COMMENT '商户外部售后单号',
  `source_type` varchar(32) DEFAULT NULL COMMENT '售后来源：MERCHANT/ZHIMA_RENT',
  `aftersale_type` varchar(64) DEFAULT NULL COMMENT '售后类型',
  `aftersale_status` varchar(32) DEFAULT NULL COMMENT '支付宝售后状态',
  `finished` tinyint(1) DEFAULT NULL COMMENT '支付宝侧是否完结',
  `apply_time` datetime DEFAULT NULL COMMENT '支付宝侧申请时间',
  `last_operation_type` varchar(64) DEFAULT NULL COMMENT '最近一次操作类型',
  `next_operation_types` varchar(512) DEFAULT NULL COMMENT '下一步可操作动作，逗号分隔',
  `need_operation` varchar(8) DEFAULT NULL COMMENT '是否需要商家处理',
  `fee_type` varchar(64) DEFAULT NULL COMMENT '费用类型',
  `reason_code` varchar(64) DEFAULT NULL COMMENT '推断出的本地原因码',
  `deduct_amount` int DEFAULT NULL COMMENT '售后金额，单位分',
  `reason_description` varchar(512) DEFAULT NULL COMMENT '原因描述',
  `matched_deduct_record_id` int DEFAULT NULL COMMENT '匹配到的本地扣减记录ID',
  `match_status` varchar(32) NOT NULL DEFAULT 'MISSING_LOCAL' COMMENT '对账状态',
  `import_status` varchar(32) NOT NULL DEFAULT 'PENDING_IMPORT' COMMENT '导入状态',
  `payload_json` mediumtext COMMENT '支付宝原始售后快照JSON',
  `fail_reason` varchar(1024) DEFAULT NULL COMMENT '同步或导入失败原因',
  `synced_at` datetime DEFAULT NULL COMMENT '最近同步时间',
  `imported_at` datetime DEFAULT NULL COMMENT '最近导入时间',
  `created_at` bigint DEFAULT NULL COMMENT '创建时间戳',
  `updated_at` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_aftersale_no` (`aftersale_no`),
  KEY `idx_order_id` (`order_id`),
  KEY `idx_order_no` (`order_no`),
  KEY `idx_out_aftersale_id` (`out_aftersale_id`),
  KEY `idx_match_import` (`match_status`, `import_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='支付宝租赁售后同步快照表';
